grades/forms.py
import re

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.fields.simple import TextAreaField, BooleanField
from wtforms.validators import DataRequired


class GradeForm(FlaskForm):
    # Fields
    grade = StringField(validators=[DataRequired("Please enter the grade of the assignment.")])
    feedback = TextAreaField(validators=[DataRequired("Please enter a the feedback of the assignment.")])
    next_steps = TextAreaField(validators=[DataRequired("Please enter the next steps of the assignment.")])
    correct = BooleanField()
    code_submission = TextAreaField(validators=[DataRequired("Please enter the code submission of the assignment.")])
    submit = SubmitField()

    # Custom validators
    def validate_grade(self, grade):
        # Check for valid grade format
        regex = re.compile(r'^[A-FU]$')
        # If date does not match regex, raise ValidationError
        if not regex.match(grade.data):
            raise ValidationError("Grade must be A, B, C, D, F, or U.")

grades/views.py
from flask import Blueprint, render_template, flash, request
from flask_login import login_required, current_user

from app import db
from grades.forms import GradeForm
from models import required_roles, Grade, Assignment, User, decrypt

# CONFIG
grades_blueprint = Blueprint('grades', __name__, template_folder='templates')


# VIEWS
@grades_blueprint.route('/grades')
@login_required
@required_roles('student')
def grades():
    # Get all grades for the current user
    all_grades = Grade.query.filter_by(student_id=current_user.id).all()
    all_assignments = Assignment.query.all()

    # If there are grades
    if len(all_grades) != 0:
        return render_template('grades/grades.html',
                               grades=all_grades, assignments=all_assignments)
    else:
        flash('No grades to review.')

    return render_template('grades/grades.html')


@grades_blueprint.route('/view_grade/<id>', methods=['GET', 'POST'])
@login_required
@required_roles('student')
def view_grade(id):
    grade = Grade.query.filter_by(grade_id=id).first_or_404()
    return render_template('grades/view_grade.html', grade=grade)


@grades_blueprint.route('/grade_assignment', methods=['GET', 'POST'])
@login_required
@required_roles('teacher')
def grade_assignment():
    # Get all grades for the current user
    all_grades = Grade.query.all()
    all_assignments = Assignment.query.all()
    all_students = User.query.all()

    # If there are grades
    if len(all_grades) != 0:
        return render_template('grades/grade_assignment.html',
                               grades=all_grades,
                               assignments=all_assignments,
                               students=all_students,
                               name=current_user.firstname)
    else:
        flash('No grades to review.')

    return render_template('grades/grade_assignment.html',
                           name=current_user.firstname)


@grades_blueprint.route('/start_grade/<id>', methods=['GET', 'POST'])
@required_roles('teacher')
def start_grade(id):
    grade = Grade.query.filter_by(grade_id=id).first_or_404()
    # First get the user id from the grade associated with the user
    user_id = grade.student_id
    # Get the postkey
    postkey = User.query.filter_by(id=user_id).first().postkey
    # Decrypt the code
    decrypted_code = decrypt(grade.code_submission, postkey)

    form = GradeForm(grade=grade.grade,
                     feedback=grade.feedback,
                     next_steps=grade.next_steps,
                     correct=grade.correct,
                     code_submission=decrypted_code)

    if form.validate_on_submit():

        # Modify grade
        grade.grade = form.grade.data
        grade.feedback = form.feedback.data
        grade.next_steps = form.next_steps.data
        grade.correct = form.correct.data
        # Add to database
        db.session.commit()

        flash('Grade modified successfully!')
        return render_template('grades/start_grade.html',
                               form=form,
                               grade=grade,
                               code=decrypted_code)

    return render_template('grades/start_grade.html',
                           form=form,
                           grade=grade,
                           code=decrypted_code)

templates/grades/grade_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Grade Assignment</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="w-full max-w-2xl mx-auto mt-5 overflow-hidden bg-white rounded-lg shadow-lg">
    <div class="px-6 py-4">
        <h3 class="mt-3 text-xl font-medium text-center text-gray-800">Welcome {{ name }}.</h3>
        <p class="mt-1 text-center text-gray-900">Grade Assignment</p>
    </div>
</div>

<div class="w-full max-w-xl mx-auto mt-5">
    {% if grades %}
        {% for grade in grades %}
        {% for assignment in assignments %}
        {% for student in students %}
            {% if assignment.assignment_id == grade.assignment_id %}
            {% if student.id == grade.student_id %}
                <div class="max-w-2xl px-8 py-4 my-4 bg-white rounded-lg shadow-lg">
                    <div class="mb-2">
                                <span class="text-xl font-bold text-gray-900" tabindex="0" role="link">
                                    {{ student.firstname }} {{ student.lastname }}
                                </span>
                        </div>
                    <div class="flex items-center justify-between">
                        <span class="text-xl font-bold text-gray-900" tabindex="0" role="link">
                                    {{ assignment.name }}
                                </span>

                        <span class="text-xl font-bold text-gray-700">
                    {% if grade.grade == "U" or grade.grade == "F" or grade.grade == "E" %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-red-700 rounded">Grade: {{ grade.grade }}</span>
                    {% elif grade.grade == "C" or grade.grade == "D" %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-yellow-600 rounded">Grade: {{ grade.grade }}</span>
                    {% else %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-green-700 rounded">Grade: {{ grade.grade }}</span>
                    {% endif %}
                </span>
                    </div>

                    <div class="mt-2">

                        <p class="mt-2 text-gray-600">
                            <b>Feedback: </b>{{ grade.feedback }}
                        </p>
                    </div>

                    <div class="flex items-center justify-between mt-4">
                        <form method="POST">
                            <input type="hidden" name="grade_id" value="{{ grade.grade_id }}">
                            <a href="{{ url_for('grades.start_grade', id=grade.grade_id) }}"
                               class="px-4 py-2 text-sm font-bold text-gray-100 bg-indigo-600 hover:text-gray-100 rounded"
                               tabindex="0" role="button">
                                Start Teacher Grading
                            </a>
                        </form>

                        <div class="flex items-center">
                                    <span class="font-bold text-gray-700">

                                </span>
                        </div>

                    </div>
                </div>
            {% endif %}
    {% endif %}
            {% endfor %}
    {% endfor %}
    {% endfor %}
    {% endif %}
</div>

{% endblock %}
</body>
</html>

templates/grades/grades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Grades</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="w-full max-w-xl mx-auto mt-5">
        {% if grades %}
            {% for grade in grades %}
                {% for assignment in assignments %}
                    {% if assignment.assignment_id == grade.assignment_id %}
                        <div class="max-w-2xl px-8 py-4 my-4 bg-white rounded-lg shadow-lg">
                            <div class="flex items-center justify-between">
                                <span class="text-xl font-bold text-gray-900" tabindex="0" role="link">
                                    {{ assignment.name }}
                                </span>

                                <span class="text-xl font-bold text-gray-700">
                    {% if grade.grade == "U" or grade.grade == "F" or grade.grade == "E" %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-red-700 rounded">Grade: {{ grade.grade }}</span>
                    {% elif grade.grade == "C" or grade.grade == "D" %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-yellow-600 rounded">Grade: {{ grade.grade }}</span>
                    {% else %}
                        <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-green-700 rounded">Grade: {{ grade.grade }}</span>
                    {% endif %}
                </span>
                            </div>

                            <div class="mt-2">

                                <p class="mt-2 text-gray-600">
                                    <b>Feedback: </b>{{ grade.feedback }}
                                </p>
                            </div>

                            <div class="flex items-center justify-between mt-4">
                                <form method="POST">
                                    <input type="hidden" name="grade_id" value="{{ grade.grade_id }}">
                                    <a href="{{ url_for('grades.view_grade', id=grade.grade_id) }}"
                                       class="px-4 py-2 text-sm font-bold text-gray-100 bg-indigo-600 hover:text-gray-100 rounded"
                                       tabindex="0" role="button">
                                        View More
                                    </a>
                                </form>

                                <div class="flex items-center">
                                    <span class="font-bold text-gray-700">

                                </span>
                                </div>

                            </div>
                            <div class="mt-4">
                                <span class="text-sm font-light text-gray-700">
                                    {% if grade.grade == 'U' %}
                                        Disclaimer: If Grade is U, this means the teacher has not graded yet.
                                    {% else %}

                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}
</body>
</html>

templates/grades/start_grade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Grade</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="w-full max-w-2xl mx-auto mt-5 overflow-hidden bg-white rounded-lg shadow-lg">
        <div class="px-6 py-4">

            <h3 class="mt-3 text-xl font-medium text-center text-gray-800">Grade Assignment</h3>

            <div class="box">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="alert alert-success">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
            </div>

            <form method="POST">
                {{ form.csrf_token() }}
                <div>
                    {{ form.grade(class="input", value=grade.grade, class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Grade") }}
                    {% for error in form.grade.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    {{ form.feedback(class="input", class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Feedback") }}
                    {% for error in form.feedback.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    {{ form.next_steps(class="input", value=grade.next_steps, class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Next Steps") }}
                    {% for error in form.next_steps.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>


                <div>
                    <span class="text-xl justify-items-center font-heavy text-gray-700">
                        Correct?
                    </span>
                    {{ form.correct(class="input", value=grade.correct, class="block h-6 w-6 w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Correct?") }}
                    {% for error in form.correct.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    {{ form.code_submission(class="input", value=code, class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Student's Code") }}
                    {% for error in form.code_submission.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div class="flex justify-center mx-auto mt-4">
                    <div>
                        {{ form.submit(class="px-6 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50") }}
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}
</body>
</html>

templates/grades/view_grade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Grade</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="w-full max-w-xl mx-auto mt-5 my-2">
        <div class="max-w-2xl px-8 py-4 bg-white rounded-lg shadow-lg">
            <div class="flex items-center justify-between my-2">
                <span class="text-xl font-bold text-gray-700">
                    {% if grade.grade == "U" or grade.grade == "F" or grade.grade == "E" %}
                    Grade: <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-red-700 rounded">{{ grade.grade }}</span>
                    {% elif grade.grade == "C" or grade.grade == "D" %}
                    Grade: <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-yellow-600 rounded">{{ grade.grade }}</span>
                    {% else %}
                    Grade: <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-green-700 rounded">{{ grade.grade }}</span>
                    {% endif %}
                </span>
            </div>

            <div class="flex items-center justify-between my-2">
            <span class="text-xl font-bold text-gray-700">
                {% if grade.correct == 1 %}
                    Assignment Correct?
                    <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-green-900 rounded">Correct</span>
                {% else %}
                    Assignment Correct?
                    <span class="px-4 py-1 text-sm font-bold text-gray-100 bg-red-900 rounded">Incorrect</span>
                {% endif %}
            </span>
            </div>

            <div>
            <span class="text-xl font-bold text-gray-700">
                Feedback:
            </span>
            <p class="mt-2 text-gray-600">{{ grade.feedback }}</p>
            </div>

            <div>
            <span class="text-xl font-bold text-gray-700">
                Next Steps:
            </span>
                <p class="mt-2 text-gray-600">{{ grade.next_steps }}</p>
            </div>

            <div>
                <span class="text-sm font-light text-gray-700">
                    Notes: If the grade is U, this may mean the assignment has not been graded by the teacher.
                    The Feedback and Next Steps may have been generated by the AI. Please contact the teacher for more information.
                    The teacher can edit the grade, feedback, and next steps.
                </span>
            </div>
        </div>
    </div>

{% endblock %}
</body>
</html>