assignments/forms.py
import re

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired


class AssignmentForm(FlaskForm):
    # Fields
    assignment_name = StringField(validators=[DataRequired("Please enter the name of the assignment.")])
    description = TextAreaField(validators=[DataRequired("Please enter a description of the assignment.")])
    due_date = StringField(validators=[DataRequired("Please enter the due date of the assignment.")])
    submit = SubmitField()

    # Custom validators
    def validate_due_date(self, due_date):
        # Check for valid date format
        regex = re.compile(r'^\d{4}-\d{2}-\d{2}$')
        # If date does not match regex, raise ValidationError
        if not regex.match(due_date.data):
            raise ValidationError("Due date must be in the format YYYY-MM-DD.")

ai/views.py
from flask import Blueprint, request, render_template, flash
from ai import llm
from app import db
from models import Assignment, Grade

ai_blueprint = Blueprint('ai', __name__, template_folder='templates')


# VIEWS
@ai_blueprint.route('/submit_assignment', methods=['GET', 'POST'])
def submit_assignment():
    assignment_id = request.form.get('assignment_id')
    code = request.form.get('code')

    # Get the assignment
    assignment = Assignment.query.filter_by(assignment_id=assignment_id).first_or_404()

    # Generate the response from the LLM
    llm.generate(assignment.description, code)
    flash('Code submitted successfully!')

    return render_template('assignments/start_assignment.html', assignment=assignment)


@ai_blueprint.route('/create_grade', methods=['GET', 'POST'])
def create_grade():
    assignment_id = request.form.get('assignment_id')
    student_id = request.form.get('student_id')
    grade = 'U'  # U for unmarked
    correct = request.form.get('correct')
    feedback = request.form.get('feedback')
    next_steps = request.form.get('next_steps')
    code_submission = request.form.get('code_submission')

    # Create the grade
    new_grade = Grade(assignment_id=assignment_id,
                      student_id=student_id,
                      grade=grade,
                      correct=correct,
                      feedback=feedback,
                      next_steps=next_steps,
                      code_submission=code_submission)

    # Add to database
    db.session.add(new_grade)
    db.session.commit()

    flash('Grade created successfully!')
    return render_template('grades/grade_assignment.html')

assignments/views.py
from flask import Blueprint, render_template, flash, request
from flask_login import current_user, login_required

from app import db
from assignments.forms import AssignmentForm
from models import Assignment, required_roles

# CONFIG
assignments_blueprint = Blueprint('assignments', __name__, template_folder='templates')


# VIEWS
@assignments_blueprint.route('/assignments', methods=['POST', 'GET'])
@login_required
@required_roles('student')
def assignments():
    # Get all assignments
    all_assignments = Assignment.query.all()

    # If there are assignments
    if len(all_assignments) != 0:
        return render_template('assignments/assignments.html',
                               assignments=all_assignments)
    else:
        flash('No assignments set.')

    return render_template('assignments/assignments.html')


@assignments_blueprint.route('/start_assignment/<id>', methods=['GET', 'POST'])
@login_required
@required_roles('student')
def start_assignment(id):
    assignment = Assignment.query.filter_by(assignment_id=id).first_or_404()
    return render_template('assignments/start_assignment.html', assignment=assignment)


@assignments_blueprint.route('/create_assignment', methods=['GET', 'POST'])
@login_required
@required_roles('teacher')
def create_assignment():
    form = AssignmentForm()

    if form.validate_on_submit():
        new_assignment = Assignment(name=form.assignment_name.data,
                                    description=form.description.data,
                                    due_date=form.due_date.data,
                                    set_by=current_user.firstname + ' ' + current_user.lastname)

        # Add to database
        db.session.add(new_assignment)
        db.session.commit()

        flash('Assignment created successfully!')
        return render_template('assignments/create_assignment.html',
                               form=form,
                               name=current_user.firstname)

    return render_template('assignments/create_assignment.html',
                           form=form,
                           name=current_user.firstname)

templates/assignments/assignments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Assignments</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="w-full max-w-xl mx-auto mt-5">
        {% if assignments %}
            {% for assignment in assignments %}
                <div class="max-w-2xl px-8 py-4 my-4 bg-white rounded-lg shadow-lg">

                    <div class="flex items-center justify-between">
                <span class="text-sm font-light text-gray-700">
                    Assignment Created: {{ assignment.created_on }}
                </span>
                        <span class="px-3 py-1 text-sm font-bold text-gray-100 bg-red-900 rounded">
                   Due on: {{ assignment.due_date }}
                </span>
                    </div>

                    <div class="mt-2">
                <span class="text-xl font-bold text-gray-900" tabindex="0" role="link">
                    {{ assignment.name }}
                </span>
                        <p class="mt-2 text-gray-600">
                            {{ assignment.description }}
                        </p>
                    </div>

                    <div class="flex items-center justify-between mt-4">
                        <form method="POST">
                        <input type="hidden" name="assignment_id" value="{{ assignment.assignment_id }}">
                        <a href="{{ url_for('assignments.start_assignment', id=assignment.assignment_id) }}"
                           class="px-4 py-2 text-sm font-bold text-gray-100 bg-indigo-600
                           hover:text-gray-100 rounded"
                           tabindex="0" role="button">
                            Start Assignment
                        </a>
                        </form>

                        <div class="flex items-center">
                    <span class="font-bold text-gray-700">
                        Set by: {{ assignment.set_by }}
                    </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}
</body>
</html>

templates/assignments/create_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Assignment</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}

    <div class="w-full max-w-2xl mx-auto mt-5 overflow-hidden bg-white rounded-lg shadow-lg">
        <div class="px-6 py-4">
            <h3 class="mt-3 text-xl font-medium text-center text-gray-800">Welcome {{ name }}.</h3>
            <p class="mt-1 text-center text-gray-900">Create Assignment</p>

            <div class="box">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="alert alert-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
            </div>

            <form method="POST">
                {{ form.csrf_token() }}
                <div>
                    {{ form.assignment_name(class="input", class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Assignment Name") }}
                    {% for error in form.assignment_name.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    {{ form.description(class="input", class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Description") }}
                    {% for error in form.description.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    {{ form.due_date(class="input", class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg focus:border-blue-400 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300 form-group",
                    placeholder="Due Date") }}
                    {% for error in form.due_date.errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>

                <div class="flex items-center justify-between mt-4">
                    <span class="text-sm text-gray-800 hover:text-gray-500">

                    </span>

                    <div>
                        {{ form.submit(class="px-6 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50") }}
                    </div>
                </div>
            </form>
        </div>

        <div class="flex items-center justify-center py-4 text-center bg-gray-50 dark:bg-gray-700"></div>

    </div>

{% endblock %}
</body>
</html>

templates/assignments/start_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start Assignment</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="box">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-success">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <form action="{{ url_for('ai.submit_assignment') }}" method="POST">
        <div>
            <label for="Description" class="block pt-4 font-bold text-xl flex justify-center mx-auto text-gray-800">
                Code Submission for {{ assignment.name }}
            </label>
            <div class="flex justify-center">
            <textarea placeholder="Paste code here!" name="code"
                      class="block mt-2 w-3/4 placeholder-gray-400/70 rounded-lg border border-gray-200 bg-white px-4 h-32 py-2.5 text-gray-700 focus:border-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40"></textarea>
            </div>

            <p class="mt-3 text-xs text-gray-400 dark:text-gray-600 flex justify-center mx-auto">
                Please paste the code inside to submit it.
            </p>

            <input type="hidden" name="assignment_id" value="{{ assignment.assignment_id }}">
            <div class="flex justify-center mx-auto mt-4">
                <button type="submit"
                        class="px-4 py-2 text-sm font-bold text-gray-100 bg-indigo-600 hover:text-gray-100 rounded"
                        tabindex="0" role="button">
                    Submit Code
                </button>
            </div>
        </div>
    </form>

{% endblock %}
</body>
</html>