assignments/views.py
from flask import Blueprint, render_template, flash, request
from flask_login import current_user, login_required

from app import db
from assignments.forms import AssignmentForm
from models import Assignment, required_roles

# CONFIG
assignments_blueprint = Blueprint('assignments', __name__, template_folder='templates')


# VIEWS
@assignments_blueprint.route('/assignments', methods=['POST', 'GET'])
@login_required
@required_roles('student')
def assignments():
    # Get all assignments
    all_assignments = Assignment.query.all()

    # If there are assignments
    if len(all_assignments) != 0:
        return render_template('assignments/assignments.html',
                               assignments=all_assignments)
    else:
        flash('No assignments set.')

    return render_template('assignments/assignments.html')


@assignments_blueprint.route('/start_assignment/<id>', methods=['GET', 'POST'])
@login_required
@required_roles('student')
def start_assignment(id):
    assignment = Assignment.query.filter_by(assignment_id=id).first_or_404()
    return render_template('assignments/start_assignment.html', assignment=assignment)


@assignments_blueprint.route('/create_assignment', methods=['GET', 'POST'])
@login_required
@required_roles('teacher')
def create_assignment():
    form = AssignmentForm()

    if form.validate_on_submit():
        new_assignment = Assignment(name=form.assignment_name.data,
                                    description=form.description.data,
                                    due_date=form.due_date.data,
                                    set_by=current_user.firstname + ' ' + current_user.lastname)

        # Add to database
        db.session.add(new_assignment)
        db.session.commit()

        flash('Assignment created successfully!')
        return render_template('assignments/create_assignment.html',
                               form=form,
                               name=current_user.firstname)

    return render_template('assignments/create_assignment.html',
                           form=form,
                           name=current_user.firstname)

grades/views.py
from flask import Blueprint, render_template, flash, request
from flask_login import login_required, current_user

from app import db
from grades.forms import GradeForm
from models import required_roles, Grade, Assignment, User, decrypt

# CONFIG
grades_blueprint = Blueprint('grades', __name__, template_folder='templates')


# VIEWS
@grades_blueprint.route('/grades')
@login_required
@required_roles('student')
def grades():
    # Get all grades for the current user
    all_grades = Grade.query.filter_by(student_id=current_user.id).all()
    all_assignments = Assignment.query.all()

    # If there are grades
    if len(all_grades) != 0:
        return render_template('grades/grades.html',
                               grades=all_grades, assignments=all_assignments)
    else:
        flash('No grades to review.')

    return render_template('grades/grades.html')


@grades_blueprint.route('/view_grade/<id>', methods=['GET', 'POST'])
@login_required
@required_roles('student')
def view_grade(id):
    grade = Grade.query.filter_by(grade_id=id).first_or_404()
    return render_template('grades/view_grade.html', grade=grade)


@grades_blueprint.route('/grade_assignment', methods=['GET', 'POST'])
@login_required
@required_roles('teacher')
def grade_assignment():
    # Get all grades for the current user
    all_grades = Grade.query.all()
    all_assignments = Assignment.query.all()
    all_students = User.query.all()

    # If there are grades
    if len(all_grades) != 0:
        return render_template('grades/grade_assignment.html',
                               grades=all_grades,
                               assignments=all_assignments,
                               students=all_students,
                               name=current_user.firstname)
    else:
        flash('No grades to review.')

    return render_template('grades/grade_assignment.html',
                           name=current_user.firstname)


@grades_blueprint.route('/start_grade/<id>', methods=['GET', 'POST'])
@required_roles('teacher')
def start_grade(id):
    grade = Grade.query.filter_by(grade_id=id).first_or_404()
    # First get the user id from the grade associated with the user
    user_id = grade.student_id
    # Get the postkey
    postkey = User.query.filter_by(id=user_id).first().postkey
    # Decrypt the code
    decrypted_code = decrypt(grade.code_submission, postkey)

    form = GradeForm(grade=grade.grade,
                     feedback=grade.feedback,
                     next_steps=grade.next_steps,
                     correct=grade.correct,
                     code_submission=decrypted_code)

    if form.validate_on_submit():

        # Modify grade
        grade.grade = form.grade.data
        grade.feedback = form.feedback.data
        grade.next_steps = form.next_steps.data
        grade.correct = form.correct.data
        # Add to database
        db.session.commit()

        flash('Grade modified successfully!')
        return render_template('grades/start_grade.html',
                               form=form,
                               grade=grade,
                               code=decrypted_code)

    return render_template('grades/start_grade.html',
                           form=form,
                           grade=grade,
                           code=decrypted_code)

users/views.py
from datetime import datetime

import bcrypt

from flask import Blueprint, render_template, flash, redirect, url_for, session
from flask_login import login_user, login_required, current_user, logout_user
from markupsafe import Markup

from app import db
from users.forms import RegisterForm, LoginForm
from models import User, required_roles

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# VIEWS
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # Authentication Attempts
    if not session.get('authentication_attempts'):
        session['authentication_attempts'] = 0

    # Check limit
    if session.get('authentication_attempts') >= 3:
        flash(Markup('Too many login attempts. Please try again later.'
                     '<br> Please click <a href="/reset">Here</a> to reset!'))
        return render_template('users/login.html', form=form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Check if user exists
        if user:
            # Check if password is correct using bcrypt
            if bcrypt.checkpw(form.password.data.encode('utf-8'), user.password):
                # Log user in
                login_user(user)
                user.last_login = user.current_login
                user.current_login = datetime.now()
                db.session.add(user)
                db.session.commit()

                # Check if user is a teacher
                if user.role == 'teacher':
                    return redirect(url_for('index'))
                else:
                    return redirect(url_for('index'))
            else:
                # Increment authentication attempts
                session['authentication_attempts'] += 1
                # Important to not give away information about what was incorrect
                flash('Incorrect email or password. Please try again.')
                return render_template('users/login.html', form=form)
        else:
            # Increment authentication attempts
            session['authentication_attempts'] += 1
            # Likewise here
            flash('Incorrect email or password. Please try again.')
            return render_template('users/login.html', form=form)

    return render_template('users/login.html', form=form)


@users_blueprint.route('/reset')
def reset():
    # Reset the authentication attempts]
    session['authentication_attempts'] = 0
    return redirect(url_for('users.login'))


@users_blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # Create Form
    form = RegisterForm()

    # Validate Form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # If user exists already
        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # Create new user
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        password=form.password.data,
                        role='student')

        # Add to DB
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('users.login'))

    # If request is GET or form is invalid render the register page
    return render_template('users/register.html', form=form)

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <!-- Mobile menu button-->
                <button type="button"
                        class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                        aria-controls="mobile-menu" aria-expanded="false">
                    <span class="absolute -inset-0.5"></span>
                    <span class="sr-only">Open main menu</span>
                    <!--
                      Icon when menu is closed.

                      Menu open: "hidden", Menu closed: "block"
                    -->
                    <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                         aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                              d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
                    </svg>
                    <!--
                      Icon when menu is open.

                      Menu open: "block", Menu closed: "hidden"
                    -->
                    <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                         aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                </button>
            </div>

            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <div class="flex flex-shrink-0 items-center">
                    <a href="{{ url_for('index') }}">
                    <img class="h-8 w-auto" src="/static/img/logo.png"
                         alt="Logo">
                    </a>
                </div>

                <div class="hidden sm:ml-6 sm:block">
                    <div class="flex space-x-4">
                        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

                        <a href="{{ url_for('index') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                           aria-current="page">
                            Dashboard
                        </a>

                        {% if current_user.is_authenticated and current_user.role == 'student' %}
                        <a href="{{ url_for('assignments.assignments') }}"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
                            Assignments
                        </a>
                        {% endif %}

                        {% if current_user.is_authenticated and current_user.role == 'teacher' %}
                        <a href="{{ url_for('assignments.create_assignment') }}"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
                            Create Assignment
                        </a>
                        {% endif %}

                        {% if current_user.is_authenticated and current_user.role == 'student' %}
                        <a href="{{ url_for('grades.grades') }}"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
                            Grades
                        </a>
                        {% endif %}

                        {% if current_user.is_authenticated and current_user.role == 'teacher' %}
                        <a href="{{ url_for('grades.grade_assignment') }}"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
                            Grade Assignments
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

                <!-- Profile dropdown -->
                <div class="relative ml-3">
                    <div class="hidden sm:ml-6 sm:block">
                    <div class="flex space-x-4">
                        {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('users.login') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                           aria-current="page">Sign In
                        </a>
                        {% endif %}

                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('users.logout') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                           aria-current="page">Sign Out
                        </a>
                        {% endif %}

                        {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('users.register') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                           aria-current="page">Register
                        </a>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" id="mobile-menu">
        <div class="space-y-1 px-2 pb-3 pt-2">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium"
               aria-current="page">Dashboard</a>
            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Assignments</a>
            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Grades</a>
            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>